apiVersion: v1
kind: Service
metadata:
  labels:
    version: v1
  name: todo-web-application
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    version: v1
